name: Clang Tidy Review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Optionally generate compile_commands.json

    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        config_file: '.clang-tidy'
        exclude: "test_*.c,test_*.h"
    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1