name: Memory Leak Test
on: [push, pull_request]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    name: 42valgrind
    steps:
    - uses: actions/checkout@v2
    - name: 42valgrind Leak checker
      uses: solareenlo/42valgrind-action@v1.0.3
      with:
        flags: 'sh test_valgrind.sh'
